---

- name: Add workers IPs to /etc/hosts
  blockinfile:
    path: /etc/hosts
    block: |
      10.0.0.110    k8s-worker1
      10.0.0.111    k8s-worker2
      10.0.0.112    k8s-worker3

- name: Copy binaries
  copy:
    src: "{{ item }}"
    dest: /usr/local/bin/
    owner: root
    group: root
    mode: 0755
  with_items:
    - ../../bin/kube-apiserver
    - ../../bin/kube-controller-manager
    - ../../bin/kube-scheduler

- name: Create config directory
  file:
    path: /var/lib/kubernetes
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Create k8s user
  user:
    name: k8s
    shell: /usr/sbin/nologin
    comment: "k8s user"
    createhome: no
    system: yes
    state: present

- name: Copy certificates and keys
  copy:
    src: "{{ item }}"
    dest: /var/lib/kubernetes/
    owner: root
    group: root
    mode: 0644
  with_items:
    - ../../pki/ca.pem
    - ../../pki/ca-key.pem
    - ../../pki/k8s-master.pem
    - ../../pki/k8s-master-key.pem
    - ../../pki/encryption-config.yml

- name: Copy systemd unit file
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0644
  with_items: 
    - { src: "lib/systemd/system/kube-apiserver.service.j2"          , dest: "/lib/systemd/system/kube-apiserver.service" }
    - { src: "lib/systemd/system/kube-controller-manager.service.j2" , dest: "/lib/systemd/system/kube-controller-manager.service" }
    - { src: "lib/systemd/system/kube-scheduler.service.j2"          , dest: "/lib/systemd/system/kube-scheduler.service" }
  notify:
    - restart k8s-master
  tags:
    - config

- meta: flush_handlers

- name: Configure RBAC for kubelet authorization
  run_once: yes
  local_action: shell kubectl apply -f roles/k8s-master/templates/rbac-conf/rbac.yml
  become_user: "{{ lookup('env','USER') }}"
  register: rbac_conf
  until: rbac_conf.stderr == ''
  retries: 3
  delay: 10
 
